from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
APP_DIR = BASE_DIR / "app"
DOCS_DIR = BASE_DIR / "docs"
DATA_DIR = BASE_DIR / "data"
LANCEDB_DIR = DATA_DIR / "lancedb"
NOTES_DIR = BASE_DIR / "notes"

NATIVE_SAMPLE_RATE = 48_000
TARGET_SAMPLE_RATE = 16_000
AUDIO_CHUNK_SECONDS = 3
AUDIO_BLOCK_SIZE = 4_096
AUDIO_MIN_PEAK = 0.03

WHISPER_MODEL_SIZE = "base.en"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"
GEMINI_MODEL = "gemini-3.8-flash"
GEMINI_FALLBACK_MODEL = "gemini-3.5-flash-lite"
MODEL_CHAIN = (GEMINI_MODEL, GEMINI_FALLBACK_MODEL)
RAG_TOP_K = 2
CACHE_SIMILARITY_THRESHOLD = 0.88
